"""Generate the AgriIntel Python-only backend Word document."""
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()

# Style helpers
def H1(text):
    p = doc.add_heading(text, level=1)
    return p

def H2(text):
    return doc.add_heading(text, level=2)

def H3(text):
    return doc.add_heading(text, level=3)

def P(text, bold=False, italic=False):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.bold = bold
    r.italic = italic
    return p

def CODE(text):
    p = doc.add_paragraph()
    r = p.add_run(text)
    r.font.name = "Consolas"
    r.font.size = Pt(9)
    return p

def BULLET(text):
    p = doc.add_paragraph(text, style="List Bullet")
    return p

def NUM(text):
    return doc.add_paragraph(text, style="List Number")

# Title page
title = doc.add_heading("AgriIntel — Complete Python-Only Backend", 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
P("Start-to-End Implementation Blueprint", italic=True).alignment = WD_ALIGN_PARAGRAPH.CENTER
P("Single Python backend (FastAPI + MongoDB + scikit-learn/XGBoost/LSTM + Celery + MLflow).", italic=True).alignment = WD_ALIGN_PARAGRAPH.CENTER
doc.add_paragraph()

# Architecture
H1("Final Architecture")
P("┌──────────────────────────────────────────────────────────┐")
P("│ Frontend (HTML/JS) — index.html, analysis.html, etc.     │")
P("└──────────────┬───────────────────────────────────────────┘")
P("               │ HTTPS + JWT")
P("┌──────────────▼───────────────────────────────────────────┐")
P("│ FastAPI (single Python service)                          │")
P("│   /api/auth · /api/farms · /api/market · /api/chat       │")
P("│   /predict/price · /predict/yield · /predict/risk        │")
P("│   /recommend · /admin · /health                          │")
P("└──────────────┬───────────────────────────────────────────┘")
P("               │")
P("┌──────────────▼───────────────────────────────────────────┐")
P("│ Celery Workers (background jobs)                         │")
P("│   ingest_prices · ingest_weather · ingest_yields         │")
P("│   retrain_models · send_notifications · weekly_digest    │")
P("└──────────────┬───────────────────────────────────────────┘")
P("               │")
P("┌──────────────▼───────────────────────────────────────────┐")
P("│ Data Layer                                               │")
P("│   MongoDB (Motor async) · Redis (cache+broker)           │")
P("│   S3/MinIO (model artifacts + feature store)             │")
P("│   MLflow tracking server                                 │")
P("└──────────────────────────────────────────────────────────┘")
doc.add_paragraph()

# STEP 1
H1("STEP 1 — Project & Environment Setup")
NUM("mkdir agriintel-backend && cd agriintel-backend")
NUM("python -m venv .venv && source .venv/bin/activate")
NUM("pip install --upgrade pip")
P("Install dependencies:", bold=True)
CODE("pip install fastapi uvicorn[standard] pydantic pydantic-settings")
CODE("pip install motor pymongo redis celery")
CODE("pip install python-jose[cryptography] passlib[bcrypt] python-multipart")
CODE("pip install twilio firebase-admin httpx aiohttp")
CODE("pip install pandas numpy scikit-learn xgboost lightgbm")
CODE("pip install prophet statsmodels torch mlflow optuna joblib")
CODE("pip install python-dotenv slowapi email-validator")
CODE("pip install pytest pytest-asyncio httpx")
P("Project structure:", bold=True)
CODE("agriintel-backend/")
CODE("├── app/")
CODE("│   ├── main.py")
CODE("│   ├── core/        (config, security, database, cache, logging)")
CODE("│   ├── api/v1/      (auth, farms, market, weather, chat, predict, recommend, notifications, admin, docs)")
CODE("│   ├── models/      (Pydantic schemas)")
CODE("│   ├── db/repositories/")
CODE("│   ├── services/    (auth, farm, market, weather, chat, notification, sms, push)")
CODE("│   ├── ml/")
CODE("│   │   ├── features/  (price, yield, risk)")
CODE("│   │   ├── models/    (base, seasonal_naive, prophet, xgboost, lstm, yield, risk)")
CODE("│   │   ├── training/  (train_price, train_yield, train_risk, retrain)")
CODE("│   │   ├── inference/ (price_predictor, yield_predictor, risk_predictor)")
CODE("│   │   └── pipeline.py")
CODE("│   ├── workers/     (celery_app, tasks_prices, tasks_weather, tasks_yields, tasks_retrain, tasks_notify)")
CODE("│   ├── data_pipeline/ (ingest_prices, ingest_weather, ingest_yields)")
CODE("│   └── utils/")
CODE("├── tests/")
CODE("├── scripts/         (seed_crops, seed_districts, seed_yields)")
CODE("├── models_store/")
CODE("├── feature_store/")
CODE("├── mlruns/")
CODE("├── .env")
CODE("├── docker-compose.yml")
CODE("├── Dockerfile")
CODE("└── requirements.txt")
P("Create docker-compose.yml with services: mongo, redis, minio, mlflow, api, worker, beat.", bold=False)
P("Create .env with: MONGO_URL, REDIS_URL, JWT_SECRET, JWT_REFRESH_SECRET, TWILIO_*, OPENWEATHER_KEY, AGMARKNET_API_URL, DATA_GOV_API_KEY, GROQ_API_KEY, FCM_CREDENTIALS_PATH, MLFLOW_TRACKING_URI.", bold=False)
P("Verify boot — uvicorn app.main:app --reload → GET /health returns {\"status\":\"ok\"}.", bold=False)

# STEP 2
H1("STEP 2 — Core Infrastructure (app/core/)")
H2("2.1 config.py")
NUM("Use pydantic_settings.BaseSettings")
NUM("Load from .env — Mongo URL, Redis URL, JWT secrets, API keys, MLflow URI")
NUM("Sub-configs: DatabaseSettings, AuthSettings, MLSettings, ExternalAPISettings")
H2("2.2 database.py")
NUM("mongodb.py — Motor async client, get_db() dependency")
NUM("Collection accessors: users, otps, farms, crops, market_prices, weather_daily, yield_history, recommendations, risk_scores, chat_sessions, notifications, scenarios, model_registry")
NUM("Create indexes on startup (compound indexes for queries)")
H2("2.3 cache.py")
NUM("Redis async client (redis.asyncio)")
NUM("Helpers: cache_get(key), cache_set(key, value, ttl), cache_delete(pattern)")
NUM("Namespacing: price:{crop}:{district}:{date}, weather:{district}:{date}")
H2("2.4 security.py")
NUM("JWT encode/decode (python-jose)")
NUM("Password/OTP hashing (passlib bcrypt)")
NUM("create_access_token(user_id), create_refresh_token(user_id), verify_token(token)")
H2("2.5 logging.py")
NUM("Structured JSON logger (loguru or stdlib with formatter)")
NUM("Request ID middleware")
NUM("Log to stdout + file")

# STEP 3
H1("STEP 3 — Pydantic Schemas (app/models/)")
P("One file per domain:", bold=True)
BULLET("user.py — UserCreate, UserOut, UserInDB")
BULLET("auth.py — SendOTPRequest, VerifyOTPRequest, TokenResponse")
BULLET("farm.py — FarmCreate, FarmUpdate, FarmOut")
BULLET("market.py — MarketPriceOut, PriceForecastOut, SellRecommendationOut")
BULLET("weather.py — WeatherOut, WeatherForecastDay")
BULLET("ml.py — PricePredictRequest, PricePredictResponse, YieldPredictRequest, RiskPredictRequest, RecommendationOut")
BULLET("chat.py — ChatSessionCreate, ChatMessageOut, ChatMessageRequest")
BULLET("notification.py — NotificationOut, DeviceTokenIn")
BULLET("common.py — Pagination, APIError, SuccessResponse")
P("All with model_config = ConfigDict(from_attributes=True) where needed.")

# STEP 4
H1("STEP 4 — Repositories (app/db/repositories/)")
P("Async Mongo CRUD per collection. One file per entity.", bold=True)
BULLET("user_repo.py — create_user, get_by_phone, update_language")
BULLET("otp_repo.py — create_otp, get_valid_otp, mark_used, increment_attempts")
BULLET("farm_repo.py — create, get_by_user, update, delete")
BULLET("crop_repo.py — list_all, get_by_key")
BULLET("market_repo.py — upsert_price, get_latest, get_history, save_forecast")
BULLET("weather_repo.py — upsert_daily, get_forecast")
BULLET("yield_repo.py — upsert, get_history")
BULLET("chat_repo.py — create_session, append_message, get_session, list_sessions, delete_session")
BULLET("notification_repo.py — create, list_user, mark_read")
BULLET("model_registry_repo.py — register_version, promote, get_production")

# STEP 5
H1("STEP 5 — Authentication (Phone + OTP)")
P("Build in app/api/v1/auth.py + app/services/auth_service.py:", bold=True)
BULLET("POST /api/v1/auth/send-otp")
BULLET("Validate phone (E.164 via pydantic PhoneNumber)")
BULLET("Rate limit: 3 per 10 min (slowapi)")
BULLET("Generate 6-digit code, bcrypt-hash, store in otps with expires_at = now + 5min")
BULLET("Send via sms_service.send_sms(phone, \"Your AgriIntel OTP is {code}\")")
BULLET("In dev, log to console")
BULLET("POST /api/v1/auth/verify-otp — verify hash + expiry + attempts ≤ 5, find-or-create user, issue access (15 min) + refresh (30 d) JWT")
BULLET("POST /api/v1/auth/refresh — rotate refresh")
BULLET("POST /api/v1/auth/logout — blacklist refresh")
BULLET("app/api/deps.py — get_current_user(token) → User")
BULLET("app/services/sms_service.py — Twilio wrapper, fallback to console")
BULLET("Wire agrintel_login.html to call these endpoints (replace static goToOtp)")

# STEP 6
H1("STEP 6 — Farm Profile API")
P("In app/api/v1/farms.py:", bold=True)
BULLET("POST /api/v1/farms — body FarmCreate, creates farm linked to current user")
BULLET("GET /api/v1/farms/me")
BULLET("PUT /api/v1/farms/me — partial update")
BULLET("GET /api/v1/farms/districts?state=…")
BULLET("GET /api/v1/farms/soils (7 types), /irrigations (4), /crops (9)")
BULLET("POST /api/v1/farms/geocode — {lat, lng} → reverse geocode via Google Maps → {village, district, state}")
BULLET("app/services/farm_service.py — validation, area conversion (acre ↔ hectare)")
BULLET("Wire analysis.html runAnalysis() → POST /farms then call /recommend")
BULLET("Wire dashboard.html saveFarmEdit() → PUT /farms/me")

# STEP 7
H1("STEP 7 — Data Pipelines (app/data_pipeline/)")
H2("7.1 Price Ingestion (ingest_prices.py)")
NUM("Fetch from Agmarknet / data.gov.in via httpx.AsyncClient")
NUM("For each (crop, mandi, date): validate price > 0, normalize to ₹/quintal")
NUM("Upsert into market_prices (compound key: crop+mandi+date)")
NUM("Idempotent — safe to re-run")
NUM("Backfill helper: python -m app.data_pipeline.ingest_prices --backfill --years=3")
H2("7.2 Weather Ingestion (ingest_weather.py)")
NUM("OpenWeatherMap One Call for each district")
NUM("Upsert weather_daily with current + forecast7d")
NUM("Backfill 1 year")
H2("7.3 Yield History (ingest_yields.py)")
NUM("data.gov.in district yield (q/ha) for 9 crops × 5+ years")
NUM("Upsert yield_history")
H2("7.4 Celery Beat Schedule (app/workers/celery_app.py)")
CODE('beat_schedule = {')
CODE('    "ingest-prices-daily": {"task": "tasks.ingest_prices", "schedule": crontime(6, 0)},')
CODE('    "ingest-weather-3h":   {"task": "tasks.ingest_weather", "schedule": crontime(0, "*/3")},')
CODE('    "retrain-monthly":     {"task": "tasks.retrain_models", "schedule": crontime(0, 0, day_of_month=1)},')
CODE('    "weekly-digest":       {"task": "tasks.weekly_digest", "schedule": crontime(8, 0, day_of_week=1)},')
CODE('    "price-alerts-6h":     {"task": "tasks.price_alerts", "schedule": crontime(0, "*/6")},')
CODE('    "weather-alerts-3h":   {"task": "tasks.weather_alerts", "schedule": crontime(0, "*/3")},')
CODE('}')

# STEP 8
H1("STEP 8 — Feature Engineering (app/ml/features/)")
H2("8.1 price_features.py")
P("Function build_price_features(df: pd.DataFrame) -> pd.DataFrame:", bold=True)
NUM("Sort by date")
NUM("Lags: price_t1, t3, t7, t14, t30")
NUM("Rolling: mean_7, mean_30, std_7, std_30")
NUM("Momentum: pct_change_7d, pct_change_30d")
NUM("Volatility: std_30 / mean_30")
NUM("Seasonality: sin(2π·doy/365), cos(2π·doy/365)")
NUM("Festival flags: is_diwali, is_onam, is_sankranti, is_holi (Indian agri calendar)")
NUM("Weather joins (left-join on date+district)")
NUM("Categorical encodings (target encoding for crop, district)")
H2("8.2 yield_features.py")
NUM("Soil one-hot + numeric")
NUM("Weather aggregates (growing-season totals)")
NUM("District historical mean/std")
NUM("Farm: irrigation, water, previousCrop, area")
H2("8.3 risk_features.py")
NUM("Price volatility (30d std)")
NUM("Forecast uncertainty (std across horizons)")
NUM("Weather risk score (deviation from 5-yr norm)")
NUM("Yield variance (district history)")
NUM("Input cost trend (90d % change)")
H2("8.4 Feature Store")
NUM("Offline: feature_store/{crop}/{year}.parquet (partitioned)")
NUM("Online: Redis key feat:{crop}:{district}:{date} with last 90 days")
NUM("Versioning: parquet path includes git SHA")

# STEP 9
H1("STEP 9 — ML Model Library (app/ml/models/)")
H2("9.1 base.py")
P("Abstract BaseModel with: fit(X, y), predict(X), save(path), load(path), get_params()")
H2("9.2 seasonal_naive.py")
NUM("Predict: price_t+h = price_(t-365+h) for h ∈ {7, 14, 28}")
H2("9.3 prophet_model.py")
NUM("Prophet(yearly_seasonality=True, weekly_seasonality=True)")
NUM("Add regressors: rainfall, temp, fuel_price")
NUM("fit(df_prophet), predict(future_df) -> yhat, yhat_lower, yhat_upper")
NUM("Save via joblib")
H2("9.4 xgboost_model.py")
NUM("XGBRegressor(n_estimators=500, max_depth=6, learning_rate=0.05)")
NUM("Direct multi-horizon: separate model per h")
NUM("Quantile extension for confidence intervals (objective='reg:quantileerror')")
NUM("Hyperparameter tuning with Optuna (50 trials, 5-fold TimeSeriesSplit)")
H2("9.5 lstm_model.py")
NUM("PyTorch nn.Module")
NUM("Input projection → 2× LSTM(128) → Attention → Quantile heads")
NUM("3 horizons × 3 quantiles (0.1, 0.5, 0.9)")
NUM("Loss: pinball loss")
NUM("Optimizer: Adam + ReduceLROnPlateau")
NUM("Early stopping on val MAPE")
NUM("Save state dict + scaler")
H2("9.6 yield_model.py")
NUM("XGBoost regressor + 2 quantile heads (0.1, 0.9)")
NUM("Output: q/acre")
H2("9.7 risk_model.py")
NUM("XGBClassifier (3 classes: Low, Medium, High)")
NUM("Softmax output → probabilities")
NUM("Labels from rule-based historical generation")

# STEP 10
H1("STEP 10 — Training Pipeline (app/ml/training/)")
H2("10.1 train_price.py")
NUM("Load last 3 years market_prices from Mongo")
NUM("Build features via price_features.build_price_features")
NUM("Train/val split — last 6 months as holdout")
NUM("Train all 3 baselines, log to MLflow")
NUM("Track: MAPE, RMSE, MAE, directional accuracy per horizon")
NUM("Save best model → models_store/price_{algo}_v{version}.joblib")
NUM("Register in model_registry collection + MLflow registry")
H2("10.2 train_yield.py")
NUM("Load yield_history (5+ years) + join with weather_daily + farms.soil aggregates")
NUM("Build yield features")
NUM("Train XGBoost + quantile heads")
NUM("Log to MLflow")
NUM("Save → models_store/yield_v{version}.joblib")
H2("10.3 train_risk.py")
NUM("Generate labels from historical outcomes (rule-based)")
NUM("Build risk features")
NUM("Train classifier")
NUM("Log + save → models_store/risk_v{version}.joblib")
H2("10.4 retrain.py")
NUM("Celery task — runs monthly")
NUM("Pull latest 2 years data")
NUM("Retrain top 3 candidates")
NUM("Evaluate on holdout")
NUM("If MAPE improves >2% vs production → promote")
NUM("Update model_registry.production_version")
NUM("Drift check before retraining (KS test on features)")

# STEP 11
H1("STEP 11 — Inference Layer (app/ml/inference/)")
H2("11.1 registry.py")
NUM("On startup, load all production models into memory")
NUM("LRU cache for predictions")
NUM("Fallback: if model missing, use seasonal naive")
NUM("Reload on registry update (signal from Celery)")
H2("11.2 price_predictor.py")
CODE("async def predict_price(crop, district, horizons=[7,14,28]) -> PricePredictResponse:")
CODE("    # 1. Fetch last 90 days from Mongo + Redis cache")
CODE("    # 2. Build features")
CODE("    # 3. Run model per horizon")
CODE("    # 4. Return {h7: {point, lower, upper}, h14, h28, model_version, generated_at}")
H2("11.3 yield_predictor.py")
NUM("Input: crop, district, soil, area, irrigation")
NUM("Build features, run model")
NUM("Return {point, lower, upper, unit, model_version}")
H2("11.4 risk_predictor.py")
NUM("Input: crop, district, farm_id")
NUM("Build risk features from current state")
NUM("Run classifier")
NUM("Return {overall, probabilities, breakdown, watch, model_version}")
H2("11.5 pipeline.py (Orchestrator)")
CODE("async def recommend(farm) -> RecommendationOut:")
CODE("    # 1. Score all 9 crops")
CODE("    # 2. For each: yield_pred × price_pred − cost − risk_penalty")
CODE("    # 3. Apply seasonal boost")
CODE("    # 4. Rank, return top with reasons")

# STEP 12
H1("STEP 12 — Prediction API Endpoints (app/api/v1/predict.py)")
NUM("POST /api/v1/predict/price — Body: {crop, district, state, horizons: [7,14,28]} → {h7: {point, lower, upper}, h14, h28, model_version, generated_at}, cache 1h")
NUM("POST /api/v1/predict/yield — Body: {crop, district, soil, area, irrigation, weather_window} → {point, lower, upper, unit}")
NUM("POST /api/v1/predict/risk — Body: {crop, district, farm_id?} → {overall, probabilities, breakdown, watch}")
NUM("POST /api/v1/predict/recommend — Body: {farm_id} or full farm snapshot → ranked crops")
NUM("GET /api/v1/predict/health — model load status + last inference timestamps")

# STEP 13
H1("STEP 13 — Market & Weather API (app/api/v1/)")
H2("13.1 market.py")
NUM("GET /api/v1/market/{crop} — current price, 7d/30d change, expected range")
NUM("GET /api/v1/market/{crop}/history?days=180")
NUM("GET /api/v1/market/{crop}/forecast?weeks=4 — calls /predict/price")
NUM("GET /api/v1/market/sell-recommendation/{crop} — {action, current, expected, upside, confidence, window}")
NUM("GET /api/v1/market/list — all crops summary")
NUM("All endpoints cache 1h in Redis")
H2("13.2 weather.py")
NUM("GET /api/v1/weather/current?district=&state=")
NUM("GET /api/v1/weather/forecast?district=&days=7")
NUM("GET /api/v1/weather/risk?district= — calls risk model")
NUM("Cache 30min")

# STEP 14
H1("STEP 14 — Sprout AI Chat")
P("In app/api/v1/chat.py + app/services/chat_service.py:", bold=True)
NUM("POST /api/v1/chat/sessions — create new session, auto-title from first message")
NUM("GET /api/v1/chat/sessions — list user's conversations")
NUM("GET /api/v1/chat/sessions/{id} — full thread")
NUM("DELETE /api/v1/chat/sessions/{id}")
NUM("POST /api/v1/chat/sessions/{id}/messages — body {content} → SSE stream")
NUM("Prompt assembly in chat_service.build_messages(user_id, content)")
NUM("Inject: getFarmContext(user_id) from saved farm")
NUM("Inject: latest predict_price, predict_yield, predict_risk summaries")
NUM("Inject: last N turns from session")
NUM("Streaming — call Groq chat.completions.create(stream=True), yield chunks via StreamingResponse")
NUM("Safety — PII redaction, token logging, daily quota (Celery counter)")
NUM("Frontend wire — sprout.html sendMessage() uses EventSource('/api/v1/chat/sessions/{id}/messages?content=...') or POST + ReadableStream")

# STEP 15
H1("STEP 15 — Notifications")
P("In app/api/v1/notifications.py + app/services/:", bold=True)
NUM("POST /api/v1/notifications/device-token — register FCM token")
NUM("GET /api/v1/notifications — list user notifications")
NUM("PUT /api/v1/notifications/{id}/read")
NUM("Celery tasks (app/workers/tasks_notify.py)")
NUM("price_alerts (every 6h) — for each user with threshold, check latest prediction")
NUM("weather_alerts (every 3h) — high-risk weather trigger")
NUM("weekly_digest (Monday 8 AM) — personalized summary using latest ML predictions")
NUM("push_service.py — FCM via firebase-admin")
NUM("SMS fallback via sms_service.py")
NUM("Respect settings toggles from dashboard")

# STEP 16
H1("STEP 16 — Admin & Docs")
P("In app/api/v1/admin.py and docs.py:", bold=True)
NUM("GET /api/v1/admin/users (admin role)")
NUM("GET /api/v1/admin/analytics")
NUM("POST /api/v1/admin/retrain — manual trigger")
NUM("GET /api/v1/admin/models — list registry")
NUM("GET /api/v1/docs/architecture — returns the architecture diagram")
NUM("GET /api/v1/docs/faq — FAQ list")

# STEP 17
H1("STEP 17 — Main App (app/main.py)")
NUM("Create FastAPI app")
NUM("Include all routers: app.include_router(auth.router, prefix=\"/api/v1/auth\", tags=[\"auth\"]), etc.")
NUM("CORS middleware (allow frontend origin)")
NUM("TrustedHost middleware in production")
NUM("Request ID middleware")
NUM("Exception handlers (validation, auth, not-found, 500)")
NUM("Startup event: connect Mongo, Redis, load ML models")
NUM("Shutdown event: close connections")
NUM("GET /health — checks all deps")
NUM("GET / — service info")

# STEP 18
H1("STEP 18 — Frontend Wiring")
P("The frontend (agrintel-core.js) currently calls AgriIntel.xxx. Wrap each call to hit the new FastAPI:", bold=True)
NUM("Create agrintel-api.js (new file)")
NUM("baseURL from env or config")
NUM("apiFetch(path, opts) adds Authorization: Bearer <jwt>")
NUM("Methods: sendOtp, verifyOtp, saveFarm, getMarketPrices, getYieldPrediction, getRiskAnalysis, getCropRecommendation, sendChatMessage")
NUM("Edit agrintel-core.js — keep same public API, internal calls use apiFetch")
NUM("AgriIntel.getMarketPrices(crop) → GET /api/v1/market/{crop}")
NUM("AgriIntel.getYieldPrediction(crop, farm) → POST /api/v1/predict/yield")
NUM("AgriIntel.getRiskAnalysis(crop) → POST /api/v1/predict/risk")
NUM("AgriIntel.getCropRecommendation(farm) → POST /api/v1/predict/recommend")
NUM("agrintel_login.html — replace goToOtp() with real /api/v1/auth/send-otp")
NUM("analysis.html runAnalysis() — POST /farms then /predict/recommend, store JWT")
NUM("dashboard.html — add prediction freshness timestamp + model version badge in Settings")
NUM("sprout.html sendMessage() — replace direct Groq call with server SSE")
NUM("Store JWT in localStorage (or httpOnly cookie via FastAPI)")
NUM("Add loading skeletons (already in AIApp.skeleton())")

# STEP 19
H1("STEP 19 — Security, Validation, Observability")
NUM("Pydantic validation on every request body")
NUM("slowapi rate limiting (auth: 3/10min, chat: 30/min)")
NUM("CORS allowlist")
NUM("TrustedHost middleware in production")
NUM("JWT short-lived access + rotating refresh")
NUM("bcrypt for OTP hashing")
NUM("Pydantic SecretStr for all secrets in config")
CODE("@app.exception_handler(HTTPException)")
CODE("async def http_error(request, exc):")
CODE("    return JSONResponse(status_code=exc.status_code, content={\"error\": exc.detail, \"code\": exc.status_code, \"request_id\": request.state.request_id})")
NUM("Structured logging — loguru with JSON output, request_id propagated")
NUM("Sentry — import sentry_sdk at startup with dsn")
NUM("MongoDB indexes on startup: users.phone unique, market_prices compound (crop, mandi, date), weather_daily compound (district, date), otps.expires_at TTL")
NUM("Secrets — never commit, use AWS Secrets Manager / Doppler")
NUM("Input sanitization on free-text fields (chat messages)")

# STEP 20
H1("STEP 20 — Testing (tests/)")
H2("Unit (pytest)")
BULLET("test_features.py — feature engineering correctness")
BULLET("test_models.py — model output shapes, determinism (seed RNG)")
BULLET("test_recommendation.py — scoring math")
H2("API (pytest + httpx AsyncClient)")
BULLET("test_auth.py — OTP flow happy + sad")
BULLET("test_farms.py — CRUD")
BULLET("test_market.py — forecast response shape")
BULLET("test_chat.py — session create + message")
H2("ML tests")
NUM("Model inference latency < 200ms p95 (locust or simple timer)")
NUM("Backtest on 2024 holdout before each deploy")
H2("Load + CI")
NUM("Load test — k6 on /api/v1/chat/sessions/{id}/messages — target 100 RPS")
NUM("CI — GitHub Actions: lint (ruff), pytest, build image on every PR")

# STEP 21
H1("STEP 21 — Deployment")
NUM("Dockerfile — python:3.11-slim, install requirements, copy app, uvicorn entrypoint")
P("docker-compose.yml:", bold=True)
CODE("services:")
CODE("  mongo:        { image: mongo:7, volumes: [mongo_data:/data/db] }")
CODE("  redis:        { image: redis:7 }")
CODE("  minio:        { image: minio/minio, command: server /data }")
CODE("  mlflow:       { build: ./mlflow, ports: [\"5000:5000\"] }")
CODE("  api:          { build: ., command: uvicorn app.main:app --host 0.0.0.0, ports: [\"8000:8000\"], depends_on: [mongo, redis] }")
CODE("  worker:       { build: ., command: celery -A app.workers.celery_app worker, depends_on: [mongo, redis] }")
CODE("  beat:         { build: ., command: celery -A app.workers.celery_app beat, depends_on: [redis] }")
P("Production (pick one):", bold=True)
BULLET("Render + managed Mongo + Upstash Redis (fastest MVP)")
BULLET("AWS ECS Fargate + ALB + MongoDB Atlas + ElastiCache")
BULLET("Kubernetes when scale demands")
P("CI/CD:", bold=True)
NUM("GitHub Actions: lint → test → build image → push to ECR → deploy")
NUM("Domain + HTTPS — Caddy or Cloudflare")
NUM("MLflow hosted separately with persistent volume")
NUM("Backups — Mongo daily snapshot to S3, mongodump cron")

# STEP 22
H1("STEP 22 — Launch Checklist")
BULLET("Models trained, evaluated, promoted to Production in MLflow")
BULLET("Drift monitoring active with Slack/PagerDuty alerts")
BULLET("Auth E2E (OTP → JWT → protected routes) tested")
BULLET("Chat streaming with real farm context works")
BULLET("Frontend shows live predictions with confidence bands")
BULLET("Predictions fresh within last 24h")
BULLET("Rate limits + error handling verified")
BULLET("Sentry receiving errors")
BULLET("Retraining cron scheduled + tested")
BULLET("Backup + restore tested")
BULLET("MLflow registry reflects current production versions")

# Schedule
H1("Where to Start Tomorrow")
BULLET("STEP 1 + STEP 2 + STEP 3 — Day 1 (project + core)")
BULLET("STEP 4 + STEP 5 — Days 2-3 (repos + auth)")
BULLET("STEP 7 + STEP 8 — Days 4-5 (data pipeline + features)")
BULLET("STEP 9 + STEP 10 (baseline XGBoost) — Days 6-7")
BULLET("STEP 11 + STEP 12 + STEP 13 — Days 8-9 (serving + APIs)")
BULLET("STEP 9 (LSTM) + STEP 10 (yield/risk) — Days 10-12")
BULLET("STEP 18 (frontend) — Days 13-14")
BULLET("STEP 14 (chat) + STEP 15 (notifications) — Days 15-17")
BULLET("STEP 20 (tests) + STEP 21 (deploy) — Days 18-21")
P("This gives you a working pure-Python ML-backed backend in ~3 weeks, with prices, yield, and risk all driven by models you can retrain and improve weekly. Every file is Python — no Node.js, no JS server code.", italic=True)

# Save
out = r"C:\Users\bpnsi\AgriIntel\AgriIntel_Python_Backend_Blueprint.docx"
doc.save(out)
print(f"Saved: {out}")
